version: "3.8"

services:
  db:
    container_name: socially-mysqldb
    env_file: 
      - db.env
    image: mysql:latest
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
      - 33060:33060

  backend:
    container_name: socially-backend
    env_file: 
      - server.env
    build:
      context: ./server
    volumes:
      - ./server:/server
    depends_on:
      - db
    ports:
      - 5000:5000
      
  frontend:
    container_name: socially-frontend
    env_file: 
      - client.env
    build:
      context: ./client
    volumes:
      - ./client/src:/client/src
    depends_on:
      - backend
    ports:
      - 3000:3000

volumes:
  db-data: