version: "3.8"

services:
  db:
    container_name: socially-mysqldb
    env_file: 
      - ./env/db.env
    image: mysql:8.1.0
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
      - 33060:33060

  backend:
    container_name: socially-backend
    env_file: 
      - ./env/server.env
    build:
      context: ./server
    image: shyam2056/socially-backend
    volumes:
      - ./server:/server
      - /server/node_modules
    restart: always
    depends_on:
      - db
    ports:
      - 5000:5000
      
  frontend:
    container_name: socially-frontend
    env_file: 
      - ./env/client.env
    build:
      context: ./client
    stdin_open: true
    tty: true
    image: shyam2056/socially-frontend
    volumes:
      - ./client/src:/client/src
      - /client/node_modules
    restart: always
    depends_on:
      - backend
    ports:
      - 3000:3000

volumes:
  db-data: