version: "3.8"

services:
  db:
    image: mysql:8.1.0
    container_name: socially-mysqldb
    env_file: 
      - ./env/db.env
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - db-network

  backend:
    image: shyam2056/socially-backend
    container_name: socially-backend
    env_file: 
      - ./env/server.env
    build:
      args:
        - NODE_ENV=development
      context: ./server
    volumes:
      - ./server:/server
      - /server/node_modules
    restart: always
    depends_on:
      - db
    ports:
      - 5000:5000
    networks:
      - db-network
      - client-network
      
  frontend:
    image: shyam2056/socially-frontend
    container_name: socially-frontend
    env_file: 
      - ./env/client.env
    build:
      args:
        - NODE_ENV=development
      context: ./client
    stdin_open: true
    tty: true
    volumes:
      - ./client/src:/client/src
      - /client/node_modules
    restart: always
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - client-network

volumes:
  db-data:
  
networks:
  db-network:
  client-network: