version: "3.8"

services:
  db:
    container_name: socially-mysqldb
    restart: always
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
      - 33060:33060
    env_file:
      - ./env/db.env
    networks:
      - socially-network

  backend:
    container_name: socially-backend
    restart: always
    build:
      context: ./server
    image: shyam2056/socially-backend
    volumes:
      - ./server:/server
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - ./env/server.env
    networks:
      - socially-network

  frontend:
    container_name: socially-frontend
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - ./env/client.env
    build:
      context: ./client
    image: shyam2056/socially-frontend
    volumes:
      - ./client/src:/client/src
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - socially-network

volumes:
  db-data:

networks:
  socially-network:
