version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: socially-node-server
    image: shyam2056/socially:latest
    ports:
      - "5000:5000"
    environment:
      CLIENT_URL: ${CLIENT_URL}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      NODE_ENV: production