name: Docker Compose Build and Push
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVER_ENV: ${{ secrets.SERVER_ENV }}
      CLIENT_ENV: ${{ secrets.CLIENT_ENV }}
      DB_ENV: ${{ secrets.DB_ENV }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create env files
      run: |
        echo $SERVER_ENV > server.env
        echo $CLIENT_ENV > client.env
        echo $DB_ENV > db.env
        
    - name: Login to Docker Hub
      run: |
        echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

    - name: Build and push Docker images
      run: |
        docker-compose up -d
        docker images
        docker ps -a
