name: Docker Compose Build and Push
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVER_ENV: ${{ secrets.SERVER_ENV }}
      CLIENT_ENV: ${{ secrets.CLIENT_ENV }}
      DB_ENV: ${{ secrets.DB_ENV }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create env files
      run: |
        mkdir -p env
        echo "$SERVER_ENV" > env/server.env
        echo "$CLIENT_ENV" > env/client.env
        echo "$DB_ENV" > env/db.env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Install Docker Compose
      run: |
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        mkdir -p $DOCKER_CONFIG/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.29.6/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
        chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

    - name: Build and push Docker images
      run: |
        docker builder prune --all --force
        docker compose build
        docker images
        docker compose push
